### ISSUE TITLE
getting error "Passphrase is incorrect".

### ISSUE THREAD

**Issue by Lucky-Rathore** [detunized/zoho-vault-sharp#1]
I got above error while decrypting user secrets. I cross-check the Passphrase and other inputs.

**Comment by detunized** [comment]
I think something changed on the server since I last looked into this. I don't support this library anymore as I have no capacity at the moment. I might look into that in the future. You're welcome to investigate.

**Comment by Lucky-Rathore** [comment]
Could you provide referenced documents?

**Comment by detunized** [comment]
There are none. Everything was reverse engineered. Maybe you could reach out to Zoho and see if they provide the official API.

**Comment by Lucky-Rathore** [comment]
Zoho has JavaScript SDK for the same. It helped. Thanks.
